#!/bin/bash
# Generated by Coding Agent
# Script to build and run the Home Banking application
echo "=== Building and Running Home Banking Application ==="
cd /Users/yuvai/IdeaProjects/Home-Banking-Vue-Java-SpringBoot/frontend
rm -rf node_modules package-lock.json
npm install
cd ..
mvn clean install -DskipTests
cd backend
mvn spring-boot:run
